version: 0.0

os: linux

files:
  - source: /
    destination: /opt/apache-tomcat-8.5.35/webapps/ui
    overwrite: true

permissions:
  - object: /opt/apache-tomcat-8.5.35/webapps/ui
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
