version: 0.0

os: linux

files:
  - source: /artifactout/
    destination: /home/ubuntu/app
    overwrite: true

permissions:
  - object: /home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: /home/ubuntu/app/start_server.sh
      timeout: 300
      runas: root
