version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      java: corretto17
    commands:
      - echo "Checking for the latest repos"
      - pip install requests 
      - python check_latest_commit.py
      - export CONTENT=$(cat out.txt)
      - echo "Content of out.txt: $CONTENT"

  pre_build:
    commands:
      - echo "Pre-build phase started on date"
      - mvn --version
      - |
        if [ "$CONTENT" = "backend" ]; then  # Added space around the "=" operator
          echo "Updating apt-get"
          apt-get update
          echo "Installing Maven"
          apt-get install -y maven
        else
          echo "No backend update detected. Skipping pre-build and exiting..."
          exit 0
        fi

  build:
    commands:
      - |
        if [ "$CONTENT" = "backend" ]; then  # Added space around the "=" operator
          echo "Build started on date"
          echo "Building the Maven project..."
          mvn clean install
        else
          echo "No backend update detected. Skipping build and exiting..."
          exit 0
        fi
        
  post_build:
    commands:
      - echo "Post-build phase started on date"
      - echo "Test comment"

artifacts:
  files:
    - target/*.war
  discard-paths: yes
