version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specifies Node.js version 18 for the build environment
      python: 3.9  # Ensure Python is available

  pre_build:
    commands:
      - "echo Checking for the latest updated repository..."
      - "pip install requests"  # If `urllib` doesn't work as expected, you can use `requests`
      - "python check_latest_commit.py"  # Call the Python script to check the latest commit
      - "export CONTENT=$(cat out.txt)"  # Store the result in a variable
      - "echo Content of out.txt: $CONTENT"

  build:
    commands:
      - |
        if [ "$CONTENT" = "frontend" ]; then
          echo "Detected frontend update. Proceeding with build..."
          npm install   # Installs all dependencies listed in package.json
          npm run build # Runs the build script defined in package.json
        else
          echo "No frontend update detected. Skipping build..."
          exit 0
        fi

artifacts:
  files:
    - "public/**/*"    # Includes all files in the public directory and its subdirectories
    - "src/**/*"       # Includes all files in the src directory and its subdirectories
    - "package.json"   # Includes the package.json file
    - "appspec.yml"    # Includes the appspec.yml file (for CodeDeploy)
    - "scripts/**/*"   # Includes all files in the scripts directory and its subdirectories
    - "build/**/*"     # Includes all files in the build directory and its subdirectories
