version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - >
        if git diff --quiet HEAD~1 HEAD -- ./src ./public ./scripts
        ./package.json; then
          echo "No relevant changes detected, skipping build."
          exit 0
        else
          npm run build
        fi
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - build/**/*
  discard-paths: yes
  base-directory: build
  enable-symlinks: yes
