version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18  # Specifies Node.js version 18 for the build environment

  pre_build:
    commands:
      - "echo Downloading out.txt from S3..."
      - "curl -o out.txt https://codepipeline-ap-south-1-402428956422.s3.ap-south-1.amazonaws.com/outart/out.txt"
      - "export CONTENT=$(cat out.txt)"
      - "echo Content of out.txt: $CONTENT"

  build:
    commands:
      - if [ "$CONTENT" = "frontend" ]; then
      - "echo Detected frontend update. Proceeding with build..."
      - "npm install"   # Installs all dependencies listed in package.json
      - "npm run build" # Runs the build script defined in package.json
      - else
      - "echo No frontend update detected. Skipping build..."
      - "exit 0"
      - fi

artifacts:
  files:
    - "public/**/*"    # Includes all files in the public directory and its subdirectories
    - "src/**/*"       # Includes all files in the src directory and its subdirectories
    - "package.json"   # Includes the package.json file
    - "appspec.yml"    # Includes the appspec.yml file (for CodeDeploy)
    - "scripts/**/*"   # Includes all files in the scripts directory and its subdirectories
    - "build/**/*"     # Includes all files in the build directory and its subdirectories
